# Generated by Django 4.2.30 on 2026-10-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('mensaje', models.TextField()),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Contactado', 'Contactado'), ('Rechazado', 'Rechazado'), ('Completado', 'Completado')], default='Pendiente', max_length=20)),
                ('servicio_solicitado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.servicio')),
            ],
        ),
    ]
